<a href="https://colab.research.google.com/github/jecordjotse/hamoye/blob/master/Graded_Quiz_Intro_to_Python_ML_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import pandas.util.testing as tm

In [3]:
fuel_data = pd.read_csv('https://raw.githubusercontent.com/WalePhenomenon/climate_change/master/fuel_ferc1.csv')

In [4]:
fuel_data.head()

record_id  ...  fuel_cost_per_mmbtu
0   f1_fuel_1994_12_1_0_7  ...                1.121
1  f1_fuel_1994_12_1_0_10  ...                1.120
2   f1_fuel_1994_12_2_0_1  ...                1.650
3   f1_fuel_1994_12_2_0_7  ...                1.970
4  f1_fuel_1994_12_2_0_10  ...                2.570

[5 rows x 11 columns]

In [5]:
fuel_data.describe()

utility_id_ferc1  ...  fuel_cost_per_mmbtu
count      29523.000000  ...         29523.000000
mean         118.601836  ...            19.304354
std           74.178353  ...          2091.540939
min            1.000000  ...           -41.501000
25%           55.000000  ...             1.940000
50%          122.000000  ...             4.127000
75%          176.000000  ...             7.745000
max          514.000000  ...        359278.000000

[8 rows x 7 columns]

#Question 1

In [18]:
A=[1,2,3,4,5,6]
B=[13, 21, 34]

In [16]:
A.append(B)
A

[1, 2, 3, 4, 5, 6, [13, 21, 34]]

In [19]:
A.extend(B)
A

[1, 2, 3, 4, 5, 6, 13, 21, 34]

# Question 2

In [20]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
np.array([[1,0,0],[0,1,0],[0,0,1]])

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [24]:
np.eye(3) #not eye() alone

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
np.array[(1,0,0),(0,1,0),(0,0,1)] #error

TypeError: ignored

In [26]:
np.array([1,0,0],[0,1,0],[0,0,1]) #error

ValueError: ignored

# Question 3

In [110]:
fuel_data.groupby('fuel_type_code_pudl')['fuel_cost_per_unit_burned'].describe()['min']

fuel_type_code_pudl
coal         67.421830
gas          13.659397
nuclear    4955.157002
oil         168.877086
other        18.253856
waste        19.518122
Name: fuel_cost_per_unit_burned, dtype: float64

In [111]:
fuel_data.groupby('fuel_type_code_pudl')['fuel_cost_per_unit_burned'].mean()

fuel_type_code_pudl
coal         67.421830
gas          13.659397
nuclear    4955.157002
oil         168.877086
other        18.253856
waste        19.518122
Name: fuel_cost_per_unit_burned, dtype: float64

# Question 4

In [42]:
fuel_data['fuel_mmbtu_per_unit'].describe().loc[['std','75%']].round(2)

std    10.60
75%    17.01
Name: fuel_mmbtu_per_unit, dtype: float64

# Question 5

In [48]:
fuel_data['fuel_qty_burned'].skew().round(2)

15.85

In [47]:
fuel_data['fuel_qty_burned'].kurtosis().round(2)

651.37

# Question 6

In [62]:
fuel_data.isnull().sum()[fuel_data.isnull().sum()>0].round(3)


fuel_unit    180
dtype: int64

In [61]:
(fuel_data.isnull().sum()/fuel_data.count())[fuel_data.isnull().sum()/fuel_data.count()>0].round(3)

fuel_unit    0.006
dtype: float64

# Question 8

In [67]:
fuel_data.corr().loc['fuel_cost_per_unit_burned'].sort_values()

utility_id_ferc1               -0.037863
fuel_qty_burned                -0.018535
fuel_mmbtu_per_unit            -0.010034
fuel_cost_per_mmbtu            -0.000437
fuel_cost_per_unit_delivered    0.011007
report_year                     0.013599
fuel_cost_per_unit_burned       1.000000
Name: fuel_cost_per_unit_burned, dtype: float64

# Question 9


In [92]:
new_data = fuel_data.groupby(['fuel_type_code_pudl','report_year']).sum().loc['coal'].iloc[0:5]['fuel_cost_per_unit_burned']
new_data

report_year
1994    14984.572
1995    14571.785
1996    12694.803
1997    43742.178
1998    11902.597
Name: fuel_cost_per_unit_burned, dtype: float64

In [101]:
((new_data.iloc[4]-new_data.iloc[0])/new_data.iloc[0] * 100).round(0)

-21.0

# Question 10

In [109]:
fuel_data.groupby(['report_year']).sum()['fuel_cost_per_unit_delivered'].sort_values()

report_year
1999    2.682921e+04
1995    3.931506e+04
2017    4.587348e+04
2006    4.805125e+04
2005    5.258506e+04
2007    5.476283e+04
2002    5.735121e+04
2003    6.740849e+04
2008    7.194631e+04
2011    7.412059e+04
2012    7.581617e+04
1994    7.859053e+04
2001    8.142834e+04
2016    1.074344e+05
2010    1.158381e+05
2004    1.663129e+05
2013    2.065968e+05
2014    2.256952e+05
1998    3.178799e+05
2015    3.569033e+05
2018    4.748057e+05
2009    7.975923e+05
2000    1.352903e+06
1996    1.000602e+07
1997    1.218738e+07
Name: fuel_cost_per_unit_delivered, dtype: float64